#! /bin/bash
yes() {
    cd /home/playground
    rm -rf ./{*,.*} && cargo init --vcs none
}

no() {
    exit 0
}

if [[ "$FEATURE_RESET" != "1" ]]; then
    echo "Feature not enabled, you may enable it by setting the environment varaible FEATURE_RESET to 1."
    echo "Beware this is a destructive feature and will wipe out all your data."
    exit 0
fi

echo "Warning! This is a destructive feature and will wipe out all your data in the playground."
echo ""
echo "To download a copy of your data, you can archive everything in the playground folder then use the live server"
echo "extension of vs code to serve the directory and download it. You may also use another method to backup them"
echo "including using a git repository."
echo ""
echo "Are you sure you want to proceed? (y/n)"
read answer

case $answer in
    [yY]* ) yes;;
    [nN]* ) no;;
    * ) echo "Invalid input";;
esac
